### ISSUE TITLE
使用smsforwarder的bark无法正确推送

### ISSUE THREAD

**Issue by ashesofdream** [LeslieLeung/heimdallr#164]
To Reproduce

1. 部署到vercel，配置企业微信
2. 使用smsforwarder填入https://url/token/
3. 点击smsforwarder的测试，报错307，且没有发送信息

**Comment by LeslieLeung** [comment]
看看 vercel 端有没有日志。

另外，已知有另外一个问题 #160，似乎在 vercel 上部署，路径含有中文会出问题。
