### ISSUE TITLE
Vercel 部署失败

### ISSUE THREAD

**Issue by jiz4oh** [LeslieLeung/heimdallr#168]
**Describe the bug**

如题

**To Reproduce**

点击部署 vercel

**Expected behavior**

部署成功

**Screenshots**

<img width="676" alt="image" src="https://github.com/user-attachments/assets/03e1d8a9-afc2-4ed4-9e9c-e0814d367279" />

**Runtime (please complete the following information):**
 - Runtime [e.g. Tencentcloud SCF]

**Additional context**

**Comment by coffoxo** [comment]
The conflict is caused by:
    The user requested starlette==0.42.0
    fastapi 0.115.6 depends on starlette<0.42.0 and >=0.40.0
--------
fastapi 和 starlette 版本冲突了，可以按提示在自己的仓库里修改 requirements.txt 第325行附带要修一个sha256值：

starlette==0.41.3; python_version >= "3.11" and python_version < "4.0" \
    --hash=sha256:44cedb2b7c77a9de33a8b74b2b90e9f50d11fcf25d8270ea525ad71a25374ff7 \

然后就不会报错成功部署了，至于使用受不受影响，不清楚，自己试吧
