### ISSUE TITLE
smtp发送通知报错

### ISSUE THREAD

**Issue by hausen1012** [LeslieLeung/heimdallr#39]
**Describe the bug**
使用最新版docker镜像，smtp发送通知报错
**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/LeslieLeung/heimdallr/assets/50026605/d1659ca0-e934-4552-8fe3-d0b7f6351488)

**Runtime (please complete the following information):**
 - Runtime [e.g. Tencentcloud SCF]

**Additional context**

**Comment by hausen1012** [comment]
好的感谢，等我有时间尝试一下

**Comment by hausen1012** [comment]
同时希望可以精简一下docker部署方式，比如容器启动时自动在 conf 目录下生成配置文件，程序自行判断数据库是否需要初始化而不是在配置文件中填写。

谢谢大佬开源，辛苦了

**Comment by hausen1012** [comment]
最新版docker镜像还是有同样的问题

**Comment by LeslieLeung** [comment]
确认能够复现问题，通常是 SMTP 配置有问题导致，已知如果 SMTP 域名出错会导致。

**Comment by LeslieLeung** [comment]
增加了一个异常捕获，如果是域名填错了，会有以下的提示：

```
ERROR:heimdallr.channel.email:Email send failed: [Errno 8] nodename nor servname provided, or not known
```

当然还请检查一下你的配置是否有误，以及更新配置后需要重启一下容器。@hausen1012

**Comment by hausen1012** [comment]
我看了一下，不是域名错误，似乎是一定需要 587端口才行，465不行，我用的qq的smtp。

**Comment by dustsoar** [comment]
请问 这个bug修复了吗？

**Comment by LeslieLeung** [comment]
> 请问 这个bug修复了吗？

已经修复了的，如果还有 SMTP 相关的报错可以开新的 issue 讨论。
