### ISSUE TITLE
企业微信渠道疑问

### ISSUE THREAD

**Issue by s0urcelab** [LeslieLeung/heimdallr#4]
企业微信自建应用需要绑定可信域名/可信IP，请问这块怎么解决？

**Comment by LeslieLeung** [comment]
这里使用的是[自建应用](https://open.work.weixin.qq.com/help2/pc/15381)，详情见文档

**Comment by s0urcelab** [comment]
> 这里使用的是[自建应用](https://open.work.weixin.qq.com/help2/pc/15381)，详情见文档

对啊，就是自建应用啊，现在企业微信政策要求必须绑定可信IP，除非你是今年上半年之前创建的应用，只要是新创建都存在这个问题

**Comment by LeslieLeung** [comment]
最近因为新接入chatgpt尝试了一下，如果要添加可信IP，只需要保证自己有一个公网IP即可，例如使用云服务器或者云函数都行。如果是云函数，固定IP的方式可以看 https://cloud.tencent.com/document/product/583/38198
