### ISSUE TITLE
能否支持发送图片/附件 呢

### ISSUE THREAD

**Issue by Steven52065** [LeslieLeung/heimdallr#49]
现在好像只能发送文字，但像是telegram应该是支持发送图片和附件的
apprise虽然好像支持发送附件，但是好像只能发送本地的文件，对于其他不在同一服务器的应用想要发送图片就很麻烦了，总不能先把图片上传上去再发送吧
所以希望可以支持增加一个参数，可以是图片的base64或者其他的，然后自动下载图片到服务器再调用apprise发送
感谢

**Comment by LeslieLeung** [comment]
@Steven52065 最新发布的 v2.0.8 版本已经支持了，增加一个 attach 参数里面传入文件的 base64 即可，具体可以参考[接口文档](https://heimdallr.zeabur.app/docs)。
