### ISSUE TITLE
docker部署方式中的环境变量链接点开找不到环境变量的描述了

### ISSUE THREAD

**Issue by feixu0530** [LeslieLeung/heimdallr#54]
docker部署方式中的环境变量链接点开找不到环境变量的描述了

**Comment by LeslieLeung** [comment]
原环境变量文档已经移动到 https://github.com/LeslieLeung/heimdallr/blob/main/docs/Config.md，稍后更新链接

**Comment by LeslieLeung** [comment]
@feixu0530 链接已经更新。
