### ISSUE TITLE
安卓手机可以用什么方式挂后台持续接收信息呢？

### ISSUE THREAD

**Issue by itq5** [LeslieLeung/heimdallr#56]
安卓手机可以用什么方式挂后台持续接收信息呢？

**Comment by LeslieLeung** [comment]
国内的话用企业微信、飞书或者钉钉应该都可以。

**Comment by yafoo** [comment]
> 国内的话用企业微信、飞书或者钉钉应该都可以。

大佬，把我的PushMe（https://push.i-i.me/）加一下吧，专业的安卓挂后台接收消息服务

**Comment by LeslieLeung** [comment]
> > 国内的话用企业微信、飞书或者钉钉应该都可以。
> 
> 大佬，把我的PushMe（[push.i-i.me](https://push.i-i.me/)）加一下吧，专业的安卓挂后台接收消息服务

收到，不错的应用，我近期加上。
