### ISSUE TITLE
可以加个管理后台吗？

### ISSUE THREAD

**Issue by igsood** [LeslieLeung/heimdallr#60]
https://github.com/engigu/Message-Push-Nest
像这种的界面配置

**Comment by LeslieLeung** [comment]
有考虑，但是加管理后台会让整体部署变重（例如需要数据库，需要提供前端页面服务等），我个人还是比较喜欢轻量的版本（毕竟配置变更不是很频繁）。
最近新增加的[配置生成器](https://heimdallr-configurator.vercel.app/)一定程度上能作为管理后台，看看能不能满足你的需求呢？

**Comment by igsood** [comment]
已经更新了吗？

**Comment by igsood** [comment]
有没有二维码，赞赏下。
请问有想过tg或者qq交流群吗

**Comment by LeslieLeung** [comment]
https://t.me/heimdallr_notification 建了个tg的交流群，可以来聊聊
