### ISSUE TITLE
【功能需求】Group的嵌套

### ISSUE THREAD

**Issue by KeithW0726** [LeslieLeung/heimdallr#72]
LeslieLeung 你好，

这个项目运行起来非常稳定省心，我很快就开始配置了20+个渠道，10+个组，没有掉链子的时候，非常赞！

现在面临新的痛点与需求：
1. 正如上面所说，在有如此多的渠道与通知组，很容易就遇到了需要多组多发，甚至交叉发的情况。而用户为了实现这个想法，就不得不在程序使用处写多个push，较为繁琐与冗余。另外的解法，就是在配置里多写几个需要的Group，然后把需要的channel套进去。
2. 这两种做法都较为繁琐，冗余，也不那么优雅，考虑到实际应用，还要处理为此增加的配置或者脚本里多写的push，这都是可能的隐患。
3. 故基于以上场景，能否增加一个功能需求：通知组的互相嵌套，这样既能满足此场景的需求，也能大幅度提高通知渠道配置的灵活度。

**Comment by LeslieLeung** [comment]
很好的提议，在渠道比较多的情况下支持 group 嵌套确实会比较方便。

通知项目本身支持嵌套不难，但是配置面板那边可能做起来有点难，可能只能手写配置的时候用。这个改动近期会上，感谢反馈。

**Comment by LeslieLeung** [comment]
该功能已在 https://github.com/LeslieLeung/heimdallr/releases/tag/v2.0.12 上线，使用方法可见 [这里](https://github.com/LeslieLeung/heimdallr/blob/main/docs/Config.md#%E9%80%9A%E7%9F%A5%E5%88%86%E7%BB%84%E5%92%8C%E6%B8%A0%E9%81%93%E9%85%8D%E7%BD%AE)。

**Comment by KeithW0726** [comment]
灰常感谢，马上部署上线
