### ISSUE TITLE
openwrt上面可以运行这个项目嘛？

### ISSUE THREAD

**Issue by XZWJ010** [LeslieLeung/heimdallr#79]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by LeslieLeung** [comment]
如果你的 OpenWRT 上有 Docker，可以使用 Docker 来运行（镜像支持arm64和amd64，理论上兼容多数型号的软路由）。详情可参考：https://github.com/LeslieLeung/heimdallr/blob/main/docs/deploy/Docker.md 。

由于精力有限，暂时不打算做 OpenWRT 的包，当然也欢迎 pr。

**Comment by LeslieLeung** [comment]
目前国内无法直接访问 Docker Hub，建议自行寻找可用的镜像或配置对应的网络环境。

**Comment by XZWJ010** [comment]
> 目前国内无法直接访问 Docker Hub，建议自行寻找可用的镜像或配置对应的网络环境。
已经是科学上网状态了

**Comment by XZWJ010** [comment]
> 目前国内无法直接访问 Docker Hub，建议自行寻找可用的镜像或配置对应的网络环境。现在拉去成功了，是我的环境的问题，谢谢您啦

**Comment by XZWJ010** [comment]
> 目前国内无法直接访问 Docker Hub，建议自行寻找可用的镜像或配置对应的网络环境。
