### ISSUE TITLE
部署选择

### ISSUE THREAD

**Issue by shaojs321** [LeslieLeung/heimdallr#88]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
我看到阿里云，腾讯云serverless部署，现在这个都不免费能到cloudflare或者vercel上部署吗

**Comment by LeslieLeung** [comment]
Cloudflare 可能需要一定的改造，而 Vercel 不支持 Python 或 Docker 运行时。Zeabur 应该是可以免费部署（也是我目前部署的平台），又或者 sealos 也可以（这个需要一点点费用，不过可以充几块钱用很久）。

**Comment by shaojs321** [comment]
> Zeabur

Zeabur 我看不是要收费吗
<img width="1062" alt="Zeabur " src="https://github.com/LeslieLeung/heimdallr/assets/56724141/4d227ba2-7972-46ee-919a-1b877dfdd852">

**Comment by shaojs321** [comment]
> > Zeabur
> 
> Zeabur 我看不是要收费吗 <img alt="Zeabur " width="1062" src="https://private-user-images.githubusercontent.com/56724141/346456490-4d227ba2-7972-46ee-919a-1b877dfdd852.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MjIxNTgsIm5iZiI6MTcyMDQyMTg1OCwicGF0aCI6Ii81NjcyNDE0MS8zNDY0NTY0OTAtNGQyMjdiYTItNzk3Mi00NmVlLTkxOWEtMWI4NzdkZmRkODUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA2NTczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllNzViMjQ0YjVmM2U2MjM5YjIzNDJhNjAwZWExNTM3NmQ4OTcwODNkNTcxNWJkN2IzNjQ1YWI0OWQ5MmM0ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4PzFX_Qa7-LUFuVbLATd70FFPRxDLUmydwSDTiWemGM">

<img width="1392" alt="ENABLED_GROUPS=group_1" src="https://github.com/LeslieLeung/heimdallr/assets/56724141/1863704e-a647-40bd-bd55-ab81ae6c630c">

**Comment by LeslieLeung** [comment]
那 Zeabur 目前应该是没法免费部署了。你可以尝试一下以下的选项：

- https://render.com
- https://railway.app
- https://fly.io/

更多的话可以在 https://free-for.dev/#/?id=paas 或者 https://free-for.dev/#/?id=web-hosting 看下，一般来说都可以通过 Docker 镜像 + 环境变量的方式进行部署。

**Comment by KeithW0726** [comment]
关于Vercel的部署，@ LeslieLeung 可以参考这个项目如何：

这个项目是可以直接部署在Vercel上，不是用镜像的
https://github.com/hillerliao/RSSHub-python

这个项目是著名项目rsshub的Python实现版。
实现效果：提前写好既定的爬虫文件，然后通过访问不同路由的时候，来返回对应的爬取并parse好的rss文档。中间必然也有post/get之类的。

举例：此项目部署在Vercel上，URL为https://xxx.vercel.app。 需要bilibili的Up主动态的rss文档，则访问即可 https://xx.vercel.app/bilibili/up

heimdallr 的实现逻辑我不大清楚，但应该不会太复杂，可以部署在vercel上。

Vercel当前也支持Python，我记得默认3.12吧。

**Comment by LeslieLeung** [comment]
感谢 @KeithW0726 ，之前不知道 Vercel 也可以部署 Python 的项目。简单适配了一下，现在有按钮可以直接部署到 Vercel，大家可以测试一下。

[![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2Fleslieleung%2Fheimdallr&project-name=heimdallr&repository-name=heimdallr)

**Comment by KeithW0726** [comment]
我部署了，完全OK。
有一点看能不能做个小小的优化，就是访问vercel主页前端就是光秃秃的JSON，
要不要随便的放个HTML啥的，稍稍美化
![Uploading CleanShot 2024-07-08 at 18.13.59@2x.png…]()

**Comment by LeslieLeung** [comment]
> 有一点看能不能做个小小的优化，就是访问vercel主页前端就是光秃秃的JSON， 要不要随便的放个HTML啥的，稍稍美化 

不错的建议，后续有时间做一个。

**Comment by LeslieLeung** [comment]
![image](https://github.com/user-attachments/assets/271e2719-0adf-47bc-8025-b4f7cfb7804e)

新增了一个部署成功的引导页，马上发布。
